#!/usr/bin/env ruby

require "bundler/setup"
require "subdb/cli"

def display_help
  puts <<-HELP
  subdb-cli v#{Subdb::Cli::VERSION}

  Usage:
    subdb download [video_file_path] [languages]
    subdb upload [video_file_path] [subtitles_file_path]

    [languages] is a comma separated list of desired languages in priority order to download (default: en)
  HELP
end

action = ARGV[0]

begin
  case action
  when "download"
    video_file_path = ARGV[1]
    languages       = ARGV[2] || "en"

    display_help && exit if video_file_path.nil?

    Subdb::Cli.new.download(video_file_path, languages)
    puts "Subtitles file downloaded."
  when "upload"
    video_file_path     = ARGV[1]
    subtitles_file_path = ARGV[2]

    display_help && exit if video_file_path.nil? || subtitles_file_path.nil?

    Subdb::Cli.new.upload(video_file_path, subtitles_file_path)
    puts "Subtitles file uploaded."
  else
    display_help
  end
rescue Subdb::Cli::FileNotFound
  puts "File not found"
rescue Subdb::Cli::ErrorCalculatingHash
  puts "Error calculating hash for video file"
rescue Subdb::Cli::SubtitlesNotFound
  puts "Subtitles file not found at Subdb database for the given language."
rescue SubtitleUploadError
  puts "There was a problem uploading the subtitles file."
end